CREATE TABLE JOB_RESUMES
(RESUME_ID   NUMBER,
 FIRST_NAME  VARCHAR2(200),
 LAST_NAME   VARCHAR2(200),
 RESUME      CLOB);
 
INSERT INTO JOB_RESUMES
VALUES (1, 'Paul', 'Jones', EMPTY_CLOB()); --PARA JA INICIAR COM O LOCALIZADOR

COMMIT;
 
SELECT RESUME_ID, FIRST_NAME, LAST_NAME, SUBSTR(RESUME,1,30)
FROM   JOB_RESUMES;

SELECT LENGTH(RESUME), DBMS_LOB.GETLENGTH(RESUME)
FROM   JOB_RESUMES;

SELECT DBMS_LOB.SUBSTR(RESUME,DBMS_LOB.GETLENGTH(RESUME),1) 
FROM   JOB_RESUMES;

-- Inserindo dados na coluna CLOB

INSERT INTO JOB_RESUMES 
VALUES  (2, 'Robert','Johnson' , 'Project Manager - Scrum Master, Porto Alegre, RS, Brasil');

SELECT RESUME_ID, FIRST_NAME, LAST_NAME, SUBSTR(RESUME,1,30)
FROM   JOB_RESUMES;

SELECT LENGTH(RESUME), DBMS_LOB.GETLENGTH(RESUME)
FROM   JOB_RESUMES;

SELECT DBMS_LOB.SUBSTR(RESUME,DBMS_LOB.GETLENGTH(RESUME),1) 
FROM   JOB_RESUMES;

COMMIT;

CREATE OR REPLACE PROCEDURE PRC_INSERE_RESUME
(PRESUME_ID IN JOB_RESUMES.RESUME_ID%TYPE, PRESUME IN VARCHAR2) 
IS
   VRESUME_LOCALIZADOR    CLOB;
   VTAMANHO_TEXTO         NUMBER;
   VDESLOCAMENTO          NUMBER;
BEGIN
   SELECT RESUME
   INTO   VRESUME_LOCALIZADOR
   FROM   JOB_RESUMES
   WHERE  RESUME_ID = PRESUME_ID
   FOR UPDATE;

   VDESLOCAMENTO := 1;
   VTAMANHO_TEXTO := LENGTH(PRESUME);
   DBMS_LOB.WRITE(VRESUME_LOCALIZADOR,VTAMANHO_TEXTO,VDESLOCAMENTO,PRESUME);
   COMMIT;
END;

EXEC PRC_INSERE_RESUME(1,'DBA - Database administrator , Porto Alegre, RS, Brasil')

SELECT RESUME_ID, FIRST_NAME, LAST_NAME, SUBSTR(RESUME,1,30)
FROM   JOB_RESUMES;

SELECT LENGTH(RESUME), DBMS_LOB.GETLENGTH(RESUME)
FROM   JOB_RESUMES;

SELECT DBMS_LOB.SUBSTR(RESUME,DBMS_LOB.GETLENGTH(RESUME),1) 
FROM   JOB_RESUMES;

CREATE OR REPLACE PROCEDURE PRC_EXIBE_RESUME
(PRESUME_ID IN JOB_RESUMES.RESUME_ID%TYPE) 
IS
   VRESUME_LOCALIZADOR    CLOB; --LOCALIZADOR DO CLOB
   VTAMANHO_TEXTO         NUMBER;
   VDESLOCAMENTO          NUMBER; --POSICAO INICIAL
   VTEXTO                 VARCHAR2(32767);
   VLOOP                  NUMBER;
   VPOSICAO               NUMBER := 1; --POSICAO INICIAL
   VEXIBE                 VARCHAR2(240);
BEGIN
   SELECT RESUME
   INTO   VRESUME_LOCALIZADOR
   FROM   JOB_RESUMES
   WHERE  RESUME_ID = PRESUME_ID
   FOR UPDATE;

   VDESLOCAMENTO := 1; --POSICAO INICIAL
   VTAMANHO_TEXTO := DBMS_LOB.GETLENGTH(VRESUME_LOCALIZADOR); --TAMANHO DO CLOB
   DBMS_LOB.READ(VRESUME_LOCALIZADOR,VTAMANHO_TEXTO,VDESLOCAMENTO,VTEXTO); --SAIDA VTEXTO
   VLOOP := TRUNC((LENGTH(VTEXTO))/240)+1; --QUANTIDADE DE INTERACOES MAIS UM PARA CASO O NUMERO FOR DECIMAL
   FOR I IN 1 .. VLOOP LOOP
     VEXIBE := SUBSTR(VTEXTO,VPOSICAO,240);
     VPOSICAO := VPOSICAO + 240;
     DBMS_OUTPUT.PUT_LINE(VEXIBE);
   END LOOP;
   COMMIT;
END;

SET SERVEROUTPUT ON
EXEC PRC_EXIBE_RESUME(1)

EXEC PRC_EXIBE_RESUME(2)