--Causando erro
UPDATE EMPLOYEES SET SALARY = 100;

COMMIT;

SELECT SALARY FROM EMPLOYEES;

SELECT SALARY FROM EMPLOYEES AS OF TIMESTAMP(SYSTIMESTAMP - INTERVAL '1' HOUR);

DECLARE
    CURSOR C_EMPLOYEES IS
        SELECT 
            EMPLOYEE_ID,
            SALARY
        FROM
            EMPLOYEES
        AS OF TIMESTAMP(SYSTIMESTAMP - INTERVAL '1' HOUR);
BEGIN
    
    FOR V_RECORD IN C_EMPLOYEES LOOP
        UPDATE
            EMPLOYEES
        SET
            SALARY = V_RECORD.SALARY
        WHERE
            V_RECORD.EMPLOYEE_ID = EMPLOYEE_ID;
    END LOOP;
    
    COMMIT;
END;