--Tabela copia
CREATE TABLE EMPLOYEES_COPIA
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES_COPIA;

--Drop da tabela

DROP TABLE EMPLOYEES_COPIA;

SELECT * FROM USER_RECYCLEBIN;

--Restore da tabela

FLASHBACK TABLE EMPLOYEES_COPIA TO BEFORE DROP;

SELECT * FROM EMPLOYEES_COPIA;

--Drop da tabela

DROP TABLE EMPLOYEES_COPIA;

--Purge da tabela

PURGE TABLE EMPLOYEES_COPIA;
