CREATE OR REPLACE FUNCTION FNC_BUSCA_SALARIO_EMPREGADO(
    fEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
    RETURN NUMBER
IS
    vSALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT
        SALARY
    INTO
        vSALARY
    FROM
        EMPLOYEES
    WHERE
        EMPLOYEE_ID = fEMPLOYEE_ID;
    RETURN vSALARY;

EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20001,'ID FUNCIONARIO NAO ENCONTRADO:' || fEMPLOYEE_ID);
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002,'ERRO ORACLE:' || SQLCODE || SQLERRM);
END;

--Testando

SET SERVEROUTPUT ON
DECLARE
    vsalary EMPLOYEES.SALARY%TYPE := FNC_BUSCA_SALARIO_EMPREGADO(200);
BEGIN
    DBMS_OUTPUT.PUT_LINE(vsalary);
END;