CREATE OR REPLACE FUNCTION FNC_BUSCA_DEPARTAMENTO(
    fEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN VARCHAR2
IS
    vDEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT
        D.DEPARTMENT_NAME
    INTO
        vDEPARTMENT_NAME
    FROM
        DEPARTMENTS D
    JOIN
        EMPLOYEES E
    ON
        E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE
        E.EMPLOYEE_ID = fEMPLOYEE_ID;
    RETURN vDEPARTMENT_NAME;
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20001,'ID FUNCIONARIO NAO ENCONTRADO:' || fEMPLOYEE_ID);
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002,'ERRO ORACLE:' || SQLCODE || SQLERRM);
END;

--Testando

SELECT
    FIRST_NAME,
    LAST_NAME,
    FNC_BUSCA_DEPARTAMENTO(EMPLOYEE_ID) AS DEPARTAMENTO
FROM
    EMPLOYEES;

SELECT FNC_BUSCA_DEPARTAMENTO(100) FROM DUAL;