SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT  pEmployee_id PROMPT 'Digite o Id do Empregado: '
DECLARE
    vEMPLOYEE_ID     EMPLOYEES.EMPLOYEE_ID%TYPE := &pEmployee_id;
    vFIRST_NAME      EMPLOYEES.FIRST_NAME%TYPE;
    vSALARY          EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT
        FIRST_NAME,
        SALARY
    INTO
        vFIRST_NAME,
        vSALARY
    FROM
        EMPLOYEES
    WHERE 
        EMPLOYEE_ID = vEMPLOYEE_ID;
    
    DBMS_OUTPUT.PUT_LINE('NOME: '    || vFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARIO: ' || vSALARY);
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN 
        RAISE_APPLICATION_ERROR(-20001,'ID NAO ENCONTRADO: ' || vEMPLOYEE_ID);
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002,'ERRO ORACLE: ' || SQLCODE || ' ' || SQLERRM);
END;