SET SERVEROUTPUT ON
    ACCEPT pEMPLOYEE_ID PROMPT 'Digite o id do funcionario'
DECLARE
    vFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    vLAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    vJOB_ID EMPLOYEES.JOB_ID%TYPE;
    vEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE := &pEMPLOYEE_ID;
    ePresident EXCEPTION;
BEGIN
    SELECT
        FIRST_NAME,
        LAST_NAME,
        JOB_ID
    INTO
        vFIRST_NAME,
        vLAST_NAME,
        vJOB_ID
    FROM
        EMPLOYEES
    WHERE
        EMPLOYEE_ID = vEMPLOYEE_ID;
    
    IF vJOB_ID = 'AD_PRES'
    THEN 
        RAISE ePresident;
    END IF;
    
    DBMS_OUTPUT.PUT_LINE(vFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE(vLAST_NAME);
    DBMS_OUTPUT.PUT_LINE(vJOB_ID);
    
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20001,'ID FUNCIONARIO NÃO ECONTRADO:' || vEMPLOYEE_ID);
    WHEN ePresident
    THEN
        RAISE_APPLICATION_ERROR(-20002,'DADOS NAO DISPONIVEIS');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20003, SQLCODE || ':' || SQLERRM);
END;