CREATE OR REPLACE PROCEDURE PRC_TESTE_EXECUTE_EMPLOYEES_REF_CURSOR(
    pDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE DEFAULT NULL, 
    pMANAGER_ID EMPLOYEES.MANAGER_ID%TYPE DEFAULT NULL) 
IS
    vSQL VARCHAR2(600) := 'SELECT * FROM EMPLOYEES WHERE 1 = 1';
    TYPE EMPLOYEES_CURSOR_TYPE IS REF CURSOR;
    EMPLOYEES_CURSOR  EMPLOYEES_CURSOR_TYPE;
    EMPLOYEES_RECORD EMPLOYEES%ROWTYPE;
BEGIN
    
    IF pMANAGER_ID IS NOT NULL
    THEN vSQL := vSQL || ' AND MANAGER_ID = :MANAGER_ID';
    END IF;
    
    IF pDEPARTMENT_ID IS NOT NULL
    THEN vSQL := vSQL || ' AND DEPARTMENT_ID = :DEPARTMENT_ID';
    END IF;
    
    
    CASE 
        WHEN pMANAGER_ID IS NOT NULL AND pDEPARTMENT_ID IS NOT NULL
            THEN OPEN EMPLOYEES_CURSOR FOR vSQL USING pMANAGER_ID, pDEPARTMENT_ID;
        WHEN pMANAGER_ID IS NOT NULL AND pDEPARTMENT_ID IS NULL
            THEN OPEN EMPLOYEES_CURSOR FOR vSQL USING pMANAGER_ID;
        WHEN pMANAGER_ID IS NULL AND pDEPARTMENT_ID IS NOT NULL
            THEN OPEN EMPLOYEES_CURSOR FOR vSQL USING pDEPARTMENT_ID;
        ELSE
            OPEN EMPLOYEES_CURSOR FOR vSQL;
    END CASE;
    
    LOOP
        FETCH EMPLOYEES_CURSOR
        INTO EMPLOYEES_RECORD;
    EXIT WHEN EMPLOYEES_CURSOR%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.FIRST_NAME);
        DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.LAST_NAME);
        DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.SALARY);
        DBMS_OUTPUT.PUT_LINE('---------------------------');
        
    /*FOR EMPLOYEES_RECORD IN EMPLOYEES_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.FIRST_NAME);
        DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.LAST_NAME);
        DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.SALARY);
        DBMS_OUTPUT.PUT_LINE('---------------------------');
    END LOOP;*/
    
    END LOOP;
    
EXCEPTION
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002, SQLCODE || SQLERRM);
END PRC_TESTE_EXECUTE_EMPLOYEES_REF_CURSOR;

--Testando

SET SERVEROUTPUT ON
exec PRC_TESTE_EXECUTE_EMPLOYEES_REF_CURSOR(pDEPARTMENT_ID => 60);