CREATE OR REPLACE TRIGGER B_I_EMPLOYEES_TR
BEFORE INSERT ON EMPLOYEES
BEGIN
    IF 
        (UPPER(TRIM(TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE'))) IN ('SABADO','DOMINGO') OR
        TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) NOT BETWEEN 8 AND 18)
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'O CADASTRO DE EMPREGADOS SO ESTA DISPONIVEL EM HORARIO COMERCIAL DURANTE A SEMANA');
    END IF;
END;