CREATE OR REPLACE PROCEDURE PRC_AUMENTA_SALARIO(
    pEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
    pPercentual NUMBER
    ) 
IS
BEGIN
    UPDATE
        EMPLOYEES
    SET
        SALARY = SALARY * (1 + (pPercentual/100))
    WHERE
        EMPLOYEE_ID = pEMPLOYEE_ID;
    COMMIT;
EXCEPTION
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20001,'ERRO ORACLE: ' || SQLCODE || ' '|| SQLERRM);
END;

--Executando

EXEC PRC_AUMENTA_SALARIO(208,15);

COMMIT;