--Criando diretorio com o usuário SYS
CREATE OR REPLACE DIRECTORY ARQUIVOS AS 'C:\Arquivos_teste'

--Dando os privilégios para o usuário HR

GRANT READ, WRITE ON DIRECTORY ARQUIVOS TO hr;

--Gerando um arquivo TXT

CREATE OR REPLACE PROCEDURE PRO_GERA_RELATORIO_EMPREGADOS
IS
    CURSOR C_EMPLOYEES IS
        SELECT
            FIRST_NAME,
            LAST_NAME,
            JOB_ID,
            SALARY
        FROM
            EMPLOYEES;
            
    vFILE UTL_FILE.FILE_TYPE;
BEGIN

    vFILE := UTL_FILE.FOPEN('ARQUIVOS','empregados.txt','w',32767);
    
    UTL_FILE.PUT_LINE(vFILE, 'FIRST_NAME' ||';'|| 'LAST_NAME' ||';'|| 'JOB_ID' ||';'|| 'SALARY');
    
    FOR vRECORD IN C_EMPLOYEES LOOP
        UTL_FILE.PUT_LINE(vFILE, vRECORD.FIRST_NAME ||';'|| vRECORD.LAST_NAME ||';'|| vRECORD.JOB_ID ||';'|| vRECORD.SALARY);
    END LOOP;
    
    UTL_FILE.FCLOSE(vFILE);

EXCEPTION
    WHEN OTHERS
    THEN
        UTL_FILE.FCLOSE(vFILE);
        RAISE_APPLICATION_ERROR(-20002,SQLCODE || ':' ||SQLERRM);
END;

EXEC PRO_GERA_RELATORIO_EMPREGADOS;

--Lendo um arquivo TXT

CREATE OR REPLACE PROCEDURE PRO_LER_RELATORIO_EMPREGADOS(NOME_ARQUIVO IN VARCHAR2)
IS
    vFILE UTL_FILE.FILE_TYPE;
    vLINHA VARCHAR2(400);
BEGIN
    vFILE := UTL_FILE.FOPEN('ARQUIVOS', NOME_ARQUIVO, 'r', 32767);
    
    LOOP
        UTL_FILE.GET_LINE(vFILE, vLINHA);
        EXIT WHEN vLINHA IS NULL;
        DBMS_OUTPUT.PUT_LINE(vLINHA);
    END LOOP;

    UTL_FILE.FCLOSE(vFILE);
    
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        UTL_FILE.FCLOSE(vFILE);
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('ARQUIVO ' ||NOME_ARQUIVO||' LIDO COM SUCESSO');
    WHEN OTHERS
    THEN
        UTL_FILE.FCLOSE(vFILE);
        RAISE_APPLICATION_ERROR(-20002,SQLCODE || ':' ||SQLERRM);
END;

--Testando

SET SERVEROUTPUT ON
EXEC pro_ler_relatorio_empregados('empregados.txt');
