CREATE OR REPLACE PROCEDURE PRC_TESTE_EXECUTE_EMPLOYEES(
    pDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE DEFAULT NULL, 
    pMANAGER_ID EMPLOYEES.MANAGER_ID%TYPE DEFAULT NULL) 
IS
    vSQL VARCHAR2(600) := 'SELECT * FROM EMPLOYEES WHERE 1 = 1';
    TYPE employees_record_table IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
    employees_table employees_record_table;
BEGIN
    
    IF pMANAGER_ID IS NOT NULL
    THEN vSQL := vSQL || ' AND MANAGER_ID = ' || pMANAGER_ID;
    END IF;
    
    IF pDEPARTMENT_ID IS NOT NULL
    THEN vSQL := vSQL || ' AND DEPARTMENT_ID = ' || pDEPARTMENT_ID;
    END IF;
    
    EXECUTE IMMEDIATE vSQL
    BULK COLLECT INTO employees_table;
    
    FOR i IN employees_table.FIRST..employees_table.LAST LOOP
        DBMS_OUTPUT.PUT_LINE(employees_table(i).FIRST_NAME);
        DBMS_OUTPUT.PUT_LINE(employees_table(i).LAST_NAME);
        DBMS_OUTPUT.PUT_LINE(employees_table(i).SALARY);
        DBMS_OUTPUT.PUT_LINE('---------------------------');
    END LOOP;
    
EXCEPTION
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002, SQLCODE || SQLERRM);
END PRC_TESTE_EXECUTE_EMPLOYEES;

--Testando

SET SERVEROUTPUT ON
exec PRC_TESTE_EXECUTE_EMPLOYEES(pDEPARTMENT_ID => 60);