--Criando o tipo
CREATE TYPE LINHA_EMPLOYEES AS OBJECT(
    oEMPLOYEE_ID	NUMBER(6),
    oFIRST_NAME		VARCHAR2(20),
    oLAST_NAME		VARCHAR2(25),
    oEMAIL			VARCHAR2(25),
    oPHONE_NUMBER	VARCHAR2(20),
    oHIRE_DATE		DATE,
    oJOB_ID			VARCHAR2(10),
    oSALARY			NUMBER(8,2),
    oCOMMISSION_PCT	NUMBER(2,2),
    oMANAGER_ID		NUMBER(6,0),
    oDEPARTMENT_ID	NUMBER(4,0)
);

--Criando uma tabela a partir do objeto
CREATE TYPE EMPLOYEES_TABLE IS TABLE OF LINHA_EMPLOYEES;