CREATE OR REPLACE FUNCTION FNC_FETCH_EMPLOYEES_TABLE_DEPARTMENT_PIPELINED(pDEPARTMENT_ID NUMBER)
RETURN EMPLOYEES_TABLE
PIPELINED
IS
BEGIN
    FOR vRECORD IN(
        SELECT * 
        FROM
            EMPLOYEES
        WHERE
            DEPARTMENT_ID = pDEPARTMENT_ID
    )LOOP
        PIPE ROW (LINHA_EMPLOYEES(
                vRECORD.EMPLOYEE_ID,
                vRECORD.FIRST_NAME,
                vRECORD.LAST_NAME,
                vRECORD.EMAIL,
                vRECORD.PHONE_NUMBER,
                vRECORD.HIRE_DATE,
                vRECORD.JOB_ID,
                vRECORD.SALARY,
                vRECORD.COMMISSION_PCT,
                vRECORD.MANAGER_ID,
                vRECORD.DEPARTMENT_ID
                )
        );
    END LOOP;
END;

SELECT * FROM TABLE(FNC_FETCH_EMPLOYEES_TABLE_DEPARTMENT_PIPELINED(60));