CREATE OR REPLACE FUNCTION FNC_FETCH_EMPLOYEES_TABLE_DEPARTMENT(pDEPARTMENT_ID IN NUMBER) 
RETURN EMPLOYEES_TABLE
IS
    vEMPLOYEES_TABLE EMPLOYEES_TABLE := EMPLOYEES_TABLE();
BEGIN
    FOR vRECORD IN(
        SELECT * 
        FROM
            EMPLOYEES
        WHERE
            DEPARTMENT_ID = pDEPARTMENT_ID
    )LOOP
        vEMPLOYEES_TABLE.EXTEND;
        vEMPLOYEES_TABLE(vEMPLOYEES_TABLE.LAST) := LINHA_EMPLOYEES(
                vRECORD.EMPLOYEE_ID,
                vRECORD.FIRST_NAME,
                vRECORD.LAST_NAME,
                vRECORD.EMAIL,
                vRECORD.PHONE_NUMBER,
                vRECORD.HIRE_DATE,
                vRECORD.JOB_ID,
                vRECORD.SALARY,
                vRECORD.COMMISSION_PCT,
                vRECORD.MANAGER_ID,
                vRECORD.DEPARTMENT_ID
        );
    END LOOP;
    RETURN vEMPLOYEES_TABLE;
END;

BEGIN
    SELECT * FROM (FNC_FETCH_EMPLOYEES_TABLE_DEPARTMENT(60));
END;