--Tipo number

SET SERVEROUTPUT ON
DECLARE
    vNumero NUMBER(11,2):= 100;
BEGIN
    DBMS_OUTPUT.PUT_LINE(vNumero);
END;

--Tipo CHAR e VARCHAR2

SET SERVEROUTPUT ON
DECLARE
    vEstado CHAR(2) := 'GO';
    vCidade VARCHAR2(30) := 'Rio Verde';
BEGIN
    DBMS_OUTPUT.PUT_LINE(vEstado);
    DBMS_OUTPUT.PUT_LINE(vCidade);
END;