DESC USER_DEPENDENCIES;

--Verificando dependencias diretas de EMPLOYEES
SELECT * FROM USER_DEPENDENCIES WHERE REFERENCED_NAME = 'EMPLOYEES' AND REFERENCED_TYPE = 'TABLE';

--Verificando dependencias diretas e indiretas de EMPLOYEES

SELECT *
FROM USER_DEPENDENCIES
    START WITH
        REFERENCED_NAME = 'EMPLOYEES' 
        AND REFERENCED_TYPE = 'TABLE'
CONNECT BY PRIOR
    NAME = REFERENCED_NAME AND
    TYPE = REFERENCED_TYPE;
    
--Verificando se tem objetos invalidos

SELECT *
FROM
    USER_OBJECTS
WHERE
    STATUS = 'INVALID'