DBMS_SCHEDULER.CREATE_PROGRAM();

DROP TABLE AGENDA;

CREATE TABLE AGENDA(
    AGENDA_ID NUMBER,
    AGENDA_DATA DATE,
    CONSTRAINT agenda_pk PRIMARY KEY(AGENDA_ID)
);

CREATE SEQUENCE AGENDA_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOMAXVALUE
NOCYCLE;

CREATE OR REPLACE PROCEDURE INSERE_DATA_AGENDA1 IS
BEGIN
    INSERT INTO
        hr.AGENDA1
    VALUES(AGENDA_SEQUENCE.nextval, SYSDATE);
    COMMIT;
END INSERE_DATA_AGENDA1;

--Criando o programa

BEGIN
    DBMS_SCHEDULER(
    program_name => 'HR.INSERE_DATA_AGENDA1',
    program_action => 'HR.INSERE_DATA_AGENDA1',
    program_type => 'STORED_PROCEDURE',
    number_of_arguments => 0,
    comments => 'INSERE DATA AGENDA',
    enabled => 'FALSE'
    );
    
    DBMS_SCHEDULER.ENABLE(name => 'HR.INSERE_DATA_AGENDA1');
END;