DROP TABLE AGENDA1;

CREATE TABLE AGENDA1(
    AGENDA_ID NUMBER,
    AGENDA_DATA DATE,
    CONSTRAINT agenda_pk PRIMARY KEY(AGENDA_ID)
);

COMMIT;

DROP SEQUENCE AGENDA_SEQUENCE;

CREATE SEQUENCE AGENDA_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOMAXVALUE
NOCYCLE;

COMMIT;

--Criando o programa

BEGIN
    DBMS_SCHEDULER.CREATE_PROGRAM(
    program_name => 'HR.INSERE_DATA_AGENDA3',
    program_action => 'HR.INSERE_DATA_AGENDA2',
    program_type => 'STORED_PROCEDURE',
    number_of_arguments => 0,
    comments => 'INSERE DATA AGENDA',
    enabled => TRUE
    );
/*    
    DBMS_SCHEDULER.ENABLE(name => 'HR.INSERE_DATA_AGENDA1');
*/
END;