--Objetos

DESC USER_OBJECTS

SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE IN('PROCEDURE','FUNCTION');

SELECT * FROM ALL_OBJECTS WHERE OBJECT_TYPE IN('PROCEDURE','FUNCTION');

SELECT * FROM USER_OBJECTS WHERE STATUS = 'INVALID';

--Codigo fonte

DESC USER_SOURCE;

SELECT * FROM USER_SOURCE WHERE TYPE IN('PROCEDURE','FUNCTION') AND NAME = 'PRC_INSERT_EMPREGADO';

--Consultando lista de parametros

DESC PRC_INSERT_EMPREGADO;

--Consultando erros de compilação

SHOW ERRORS prc_consulta_dados_empregado;

DESC USER_ERRORS;

SELECT * FROM USER_ERRORS;