CREATE OR REPLACE PACKAGE PCK_EMPLOYEES IS

-- Variaveis globais

    vMIN_SALARY     EMPLOYEES.SALARY%TYPE;
  
-- Procedures
    
    PROCEDURE PRC_INSERT_EMPREGADO(
        pFIRST_NAME         IN VARCHAR2,
        pLAST_NAME          IN VARCHAR2,
        pEMAIL              IN VARCHAR2,
        pPHONE_NUMBER       IN VARCHAR2,
        pHIRE_DATE          IN DATE DEFAULT SYSDATE,
        pJOB_ID             IN VARCHAR2,
        pSALARY             IN NUMBER,
        pCOMMISSION_PCT     IN NUMBER,
        pMANAGER_ID         IN NUMBER,
        pDEPARTMENT_ID      IN NUMBER
    );
    
    PROCEDURE PRC_CONSULTA_DADOS_EMPREGADO(
        vEMPLOYEE_ID    IN EMPLOYEES.EMPLOYEE_ID%TYPE,
        vFIRST_NAME     OUT EMPLOYEES.FIRST_NAME%TYPE,
        vLAST_NAME      OUT EMPLOYEES.LAST_NAME%TYPE,
        vEMAIL          OUT EMPLOYEES.EMAIL%TYPE,
        vPHONE_NUMBER   OUT EMPLOYEES.PHONE_NUMBER%TYPE,
        vHIRE_DATE      OUT EMPLOYEES.HIRE_DATE%TYPE,
        vJOB_ID         OUT EMPLOYEES.JOB_ID%TYPE,
        vSALARY         OUT EMPLOYEES.SALARY%TYPE,
        vCOMMISSION_PCT OUT EMPLOYEES.COMMISSION_PCT%TYPE,
        vMANAGER_ID     OUT EMPLOYEES.MANAGER_ID%TYPE,
        vDEPARTMENT_ID  OUT EMPLOYEES.DEPARTMENT_ID%TYPE
    );
    
    PROCEDURE PRC_AUMENTA_SALARIO(
        pEMPLOYEE_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE,
        pPercentual  IN NUMBER
    );
    
-- Functions    
    
    FUNCTION FNC_BUSCA_SALARIO_EMPREGADO(fEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE) RETURN NUMBER;
END PCK_EMPLOYEES;