BEGIN
    PCK_EMPLOYEES.PRC_INSERT_EMPREGADO('John','Marston','john@gmail','55555555',SYSDATE,'IT_PROG',20000,NULL,103,60);
    COMMIT;
END;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'John' AND LAST_NAME = 'Marston';